### PR TITLE
🍒 Support plurals

### LINKED ISSUE #2: Does not seem to work for "plural "types
This plugin works great for "singular" types.

However, plural types (when there are 2 forms) are not written to the po file.

I have uploaded some screenshots which should make the issue clear.

image

image

image

### PR DESCRIPTION
**Pull request by peaceful-james**
closes #2

### CODE REVIEW

**Comment by peaceful-james** [comment]
Screenshot 2024-05-18 034719
Screenshot 2024-05-18 034745

[restart server 🙃 ]

Screenshot 2024-05-18 035457

**Comment by peaceful-james** [comment]
Hi @ravensiris 
This PR has been working for me for couple of weeks.
I think it is ready for review.

**Comment by peaceful-james** [comment]
@arturz @ravensiris Let me know if this PR needs anything else

**Review by arturz — APPROVED** [review]
LGTM. Great job!

**Pull request merged**
